version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/star-burger/staticfiles
    depends_on:
      - web
    restart: always
  web:
    build: ./star-burger
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    command: gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application --timeout 120 --workers=3 --threads=3 --worker-connections=1000
    volumes:
      - static_volume:/home/star-burger/staticfiles
      - media_volume:/home/star-burger/media
    expose:
    - 8000
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=starburger
      - POSTGRES_PASSWORD=onlyburgerscanmakepeoplehappy
      - POSTGRES_DB=starburgerdb
      
volumes:
  postgres_data:
  static_volume:
  media_volume: