# Generated by Django 3.2 on 2021-09-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=11, verbose_name='широта')),
                ('longtitude', models.DecimalField(decimal_places=9, max_digits=11, verbose_name='долгота')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
            ],
        ),
    ]
