# Generated by Django 3.2 on 2021-08-07 13:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20210807_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.product', verbose_name='продукт')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_elements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.orderelement', verbose_name='элемент заказа'),
            preserve_default=False,
        ),
    ]
