# Generated by Django 3.2 on 2021-08-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20210807_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderelement',
            old_name='amount',
            new_name='quantity',
        ),
    ]
