# Generated by Django 3.2 on 2021-08-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20210814_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryaddress',
            new_name='address',
        ),
    ]
