# Generated by Django 3.2 on 2021-08-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_orderelement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'Необработанный'), ('CC', 'Отменён'), ('CM', 'Выполнен')], default='NP', max_length=2),
        ),
    ]
