# Generated by Django 3.2 on 2021-08-19 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда доставлено'),
        ),
        migrations.AddField(
            model_name='order',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время регистрации заказа'),
        ),
    ]
