# Generated by Django 3.2 on 2021-09-22 18:50

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20210822_2147'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('additional_set', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_elements', to='foodcartapp.order', verbose_name='заказ'),
        ),
    ]
