# Generated by Django 3.2 on 2021-09-22 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20210922_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelement',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
