# Generated by Django 3.2 on 2021-09-25 13:31

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_orderelement_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='call_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Когда доставлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CS', 'Наличные'), ('CC', 'Картой курьеру'), ('CO', 'Картой онлайн')], db_index=True, default='CS', max_length=2, verbose_name='Вид оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registration_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время регистрации заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'Необработанный'), ('CC', 'Отменён'), ('CM', 'Выполнен')], db_index=True, default='NP', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
