# Generated by Django 3.2 on 2021-10-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20211010_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='registration_date',
            new_name='registration_at',
        ),
    ]
